name: Deploy dev a Testbed
on:
    push:
        branches:
            - dev
jobs:
    scp-deploy:
        name: deploy con scp
        runs-on: ubuntu-latest
        steps:
            - name: checkout branch
              uses: actions/checkout@v2
              with:
                  ref: dev
            - name: copiar arcvhivos usando ssh
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.DEV_HOST }}
                  username: ${{ secrets.DEV_USERNAME }}
                  password: ${{ secrets.DEV_PASSWORD }}
                  port: ${{ secrets.DEV_PORT }}
                  source: "wp-content/"
                  target: ${{ secrets.DEV_TARGET }}
                  strip_components: 1
